debug: false
server:
  port: 9999

security:
  user:
    password: user
  ignored: /favicon.ico
  sessions: ALWAYS
  oauth2:
    sso:
      loginPath: /

logging:
  level:
    org.springframework.security: DEBUG

---
spring:
  profiles: default
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8080/uaa/oauth/token
      userAuthorizationUri: http://localhost:8080/uaa/oauth/authorize
      clientId: myapp
      clientSecret: KDV3FT2wCMnmzwzH
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApc6d3RkcvNYy6pTI4P4F
          pz0XNZqxo1Bs9K1sXzW99K9EzVNCDy5Ws3buGM3Apx0ORc5LlteU/sZXBBBNRQFv
          4R/SG09zSU11uNhZ21B+n0JK6dUIBvOSAv+ciPTfPD8MDRotyGbhnI49jzhyt8RR
          Mqq6aMtvDwNSjZxx2my15gMBOMIG7IeFUYiDjfCq6aW0LJD94RbTZL4jYtV0cBDc
          U8B05wlIDnM9kRWQ5dTXqkMQAoeQBF3+TOdSe7FelFPnLG8CPzTzOqWTBCfGQwhL
          Ct9MmJlo/4K+/Z7KyvCiAlYA/0sk5PvVB4SlKLAoLnfF+z8IDTlGyn5fa6TPHdfm
          LwIDAQAB
          -----END PUBLIC KEY-----
      id: openid
      serviceId: ${PREFIX:}resource
