debug: false
server:
  port: 9999

security:
  user:
    password: user
  ignored: /favicon.ico
  sessions: ALWAYS
  oauth2:
    sso:
      loginPath: /login

logging:
  level:
    org.springframework.security: DEBUG

---
spring:
  profiles: default
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8080/uaa/oauth/token
      userAuthorizationUri: http://localhost:8080/uaa/oauth/authorize
      clientId: myapp
      clientSecret: KDV3FT2wCMnmzwzH
    resource:
      user-info-uri: http://localhost:8080/uaa/user
